name: Bug Report
description: Report a bug or issue with Tributary
title: "[Bug]: "
labels: ["bug"]
assignees: ["xeroc"]
projects: []
type: bug
body:
  - type: markdown
    attributes:
    value: Thanks for reporting a bug! This helps us improve Tributary.
  - type: input
    id: contact
    attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. <email@example.com> or @username on Discord/Twitter
    validations:
    required: false
  - type: textarea
    id: what-happened
    attributes:
    label: What happened?
    description: Describe the bug or issue you encountered.
    placeholder: Tell us what went wrong!
    validations:
    required: true
